# Generated by Django 4.1.3 on 2023-04-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ac_no', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=120)),
            ],
        ),
    ]
